version: '3.7'
services:
  app:
    build: .
    container_name: validator-ejector
    restart: unless-stopped
    environment:
      - EXECUTION_NODE=${EXECUTION_NODE}
      - CONSENSUS_NODE=${CONSENSUS_NODE}
      - OPERATOR_REGISTRY_ADDRESS=${OPERATOR_REGISTRY_ADDRESS}
      - OPERATOR_ID=${OPERATOR_ID}
      - MESSAGES_LOCATION=${MESSAGES_LOCATION}
      - MESSAGES_PASSWORD=${MESSAGES_PASSWORD}
      - MESSAGES_PASSWORD_FILE=${MESSAGES_PASSWORD_FILE}
      - VALIDATOR_EXIT_WEBHOOK=${VALIDATOR_EXIT_WEBHOOK}
      - BLOCKS_PRELOAD=${BLOCKS_PRELOAD}
      - HTTP_PORT=${HTTP_PORT}
      - RUN_METRICS=${RUN_METRICS}
      - RUN_HEALTH_CHECK=${RUN_HEALTH_CHECK}
      - LOGGER_LEVEL=${LOGGER_LEVEL}
      - LOGGER_FORMAT=${LOGGER_FORMAT}
      - LOGGER_SECRETS=${LOGGER_SECRETS}
      - DRY_RUN=${DRY_RUN}
    ports:
      - '${HTTP_PORT}:${HTTP_PORT}'
    volumes:
      - ./messages:/app/messages
